# rockchip board id select devices

obj-$(CONFIG_BOARD_ID)					+= board-id.o
obj-$(CONFIG_BOARD_ID_VENDOR)			+= board-id-vendor.o
obj-$(CONFIG_BOARD_ID_IDBLOCK)			+= board-id-idblock.o
obj-$(CONFIG_BOARD_ID_HW)				+= board-id-hw.o